"use client";
import {useEffect,useState} from "react";
import {createClient,type SupabaseClient} from "@supabase/supabase-js";
type Note={id:string;title:string;updated_at:string;note_type:string};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const client:SupabaseClient|null=url&&key?createClient(url,key):null;
export default function Account(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[user,setUser]=useState<string|null>(null);const[notes,setNotes]=useState<Note[]>([]);const[error,setError]=useState("");
useEffect(()=>{if(!client)return;client.auth.getUser().then(({data})=>setUser(data.user?.email??null));const {data}=client.auth.onAuthStateChange((_e,s)=>setUser(s?.user?.email??null));return()=>data.subscription.unsubscribe()},[]);
async function auth(kind:"login"|"signup"){setError("");if(!client){setError("Supabase is not configured on this deployment.");return}const r=kind==="login"?await client.auth.signInWithPassword({email,password}):await client.auth.signUp({email,password});if(r.error)setError(r.error.message)}
async function load(){if(!client)return;const r=await client.from("notes").select("id,title,updated_at,note_type").order("updated_at",{ascending:false});if(r.error)setError(r.error.message);else setNotes(r.data??[])}
function download(n:Note){const blob=new Blob([JSON.stringify({format:"snote-json-v1",note:n},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=(n.title||"snote")+".json";a.click();URL.revokeObjectURL(a.href)}
return <main className="shell section"><div className="eyebrow">Account</div><h1 className="title">Your notebook, across devices.</h1>{!user?<div className="form"><input className="input" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input className="input" placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><div className="row"><button className="button" onClick={()=>auth("login")}>Sign in</button><button className="button" onClick={()=>auth("signup")}>Create account</button></div>{error&&<p className="muted">{error}</p>}</div>:<div className="card"><p>Signed in as <b>{user}</b></p><button className="button" onClick={()=>client?.auth.signOut()}>Sign out</button><button className="button" onClick={load} style={{marginLeft:8}}>Load notes</button>{error&&<p className="muted">{error}</p>}<div>{notes.map(n=><div className="note" key={n.id}><div><b>{n.title||"Untitled"}</b><div className="muted">{new Date(n.updated_at).toLocaleString()}</div></div><button className="button" onClick={()=>download(n)}>Download JSON</button></div>)}</div></div>}</main>}
