name: Snote macOS

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Generate macOS files
        working-directory: app
        run: flutter create --platforms=macos .
      - name: Build
        working-directory: app
        run: |
          flutter pub get
          flutter build macos --release
      - name: Build iOS unsigned
        working-directory: app
        run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v4
        with:
          name: snote-macos
          path: app/build/macos/Build/Products/Release
      - uses: actions/upload-artifact@v4
        with:
          name: snote-ios-unsigned
          path: app/build/ios/iphoneos
