name: Snote Windows

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Generate Windows files
        working-directory: app
        shell: pwsh
        run: flutter create --platforms=windows .
      - name: Build
        working-directory: app
        run: |
          flutter pub get
          flutter build windows --release
      - uses: actions/upload-artifact@v4
        with:
          name: snote-windows
          path: app/build/windows/x64/runner/Release
